[Motor.SimpleMotor.PendulumJoint]
joint_name = "PendulumJoint"
mechanicalReduction = 1.0
armature = 0.0
frictionViscousPositive = -0.0
frictionViscousNegative = -0.0
frictionDryPositive = -0.0
frictionDryNegative = -0.0
frictionDrySlope = -0.0

[Motor.SimpleMotor.SecondPendulumJoint]
joint_name = "SecondPendulumJoint"
mechanicalReduction = 1.0
armature = 0.0
frictionViscousPositive = -0.0
frictionViscousNegative = -0.0
frictionDryPositive = -0.0
frictionDryNegative = -0.0
frictionDrySlope = -0.0

[Sensor.EncoderSensor.PendulumJoint]
joint_name = "PendulumJoint"
bias = [0.1]
delay = 0.020
delayInterpolationOrder = 0
noiseStd = [0.3]

[Sensor.EncoderSensor.SecondPendulumJoint]
joint_name = "SecondPendulumJoint"
bias = [0.1]
delay = 0.01
delayInterpolationOrder = 0
noiseStd = [0.2]
